In [1]:
import pandas as pd

In [21]:
csv_name = "lucas_bank.csv"
bank_df = pd.read_csv(csv_name)

In [22]:
bank_df.head()

,Filter,Date,Description,Sub-description,Type of Transaction,Amount,Balance
0,"Custom filters (select dates and amounts), Fro...",2025-09-15,bill payment,Koodo Mobile,Debit,-28.00,4063.93
1,NaN,2025-09-15,pos purchase,Apos Subway 56519 Burna,Debit,-11.54,4091.93
2,NaN,2025-09-15,pos purchase,Apos Save On Foods 2 Burna,Debit,-4.50,4103.47
3,NaN,2025-09-15,pos purchase,Apos Mr. Shawarma Ro Richm,Debit,-9.82,4107.97
4,NaN,2025-09-15,pos purchase,Apos Dollarama # 716 Vanco,Debit,-3.26,4117.79

In [24]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Filter               1 non-null      object
 1   Date                 338 non-null    object
 2   Description          338 non-null    object
 3   Sub-description      338 non-null    object
 4   Type of Transaction  338 non-null    object
 5   Amount               338 non-null    float64
 6   Balance              338 non-null    float64
dtypes: float64(2), object(5)
memory usage: 18.6+ KB

In [29]:
new_df = bank_df.copy()

In [36]:
new_df = new_df.drop('Filter', axis=1)

In [ ]:
new_df.unique

,Date,Description,Sub-description,Type of Transaction,Amount,Balance
0,2025-09-15,bill payment,Koodo Mobile,Debit,-28.00,4063.93
1,2025-09-15,pos purchase,Apos Subway 56519 Burna,Debit,-11.54,4091.93
2,2025-09-15,pos purchase,Apos Save On Foods 2 Burna,Debit,-4.50,4103.47
3,2025-09-15,pos purchase,Apos Mr. Shawarma Ro Richm,Debit,-9.82,4107.97
4,2025-09-15,pos purchase,Apos Dollarama # 716 Vanco,Debit,-3.26,4117.79

In [38]:
new_df["Date"] = pd.to_datetime(new_df["Date"], errors='coerce')

In [40]:
new_df["Amount"].describe()

count     338.000000
mean       12.023462
std       449.972904
min     -4200.000000
25%       -15.670000
50%        -7.655000
75%        -3.822500
max      5899.000000
Name: Amount, dtype: float64